# Generated by Django 4.2.29 on 2026-03-22 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('motorcycle', 'Motorcycle'), ('bus', 'Bus / Minivan'), ('truck', 'Truck'), ('other', 'Other')], max_length=20)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(max_length=30)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('category', models.CharField(choices=[('student', 'Student'), ('staff', 'Academic Staff'), ('non_academic', 'Non-Academic Staff'), ('visitor', 'Visitor'), ('official', 'Official')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('staff', 'Staff'), ('student', 'Student'), ('visitor', 'Visitor')], default='student', max_length=20)),
                ('matric_or_staff_id', models.CharField(blank=True, max_length=50)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('congestion', 'Congestion'), ('parking', 'Illegal Parking'), ('near_miss', 'Near-miss / Accident'), ('violation', 'Traffic Violation'), ('obstruction', 'Road Obstruction'), ('other', 'Other')], max_length=30)),
                ('location', models.CharField(choices=[('main_gate', 'Main Gate'), ('admin_block', 'Admin Block Road'), ('library', 'Library Parking'), ('science_block', 'Science Block'), ('hostel_road', 'Hostel Road'), ('staff_quarters', 'Staff Quarters'), ('other', 'Other')], max_length=30)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('emergency', 'Emergency')], default='normal', max_length=20)),
                ('description', models.TextField()),
                ('vehicle_plate', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('pending', 'Pending'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('reported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('vehicle_approved', 'Vehicle Approved'), ('vehicle_suspended', 'Vehicle Suspended'), ('incident_resolved', 'Incident Resolved'), ('user_suspended', 'User Suspended'), ('user_activated', 'User Activated'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField()),
                ('performed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-performed_at'],
            },
        ),
    ]
